
function botaoEx1() {
        alert("Vamos somar dois números:")
    let n1 = Number(prompt("Digite o 1º Número:"))
    let n2 = Number(prompt("Digite o 2ª Número:"))
    let res = n1 + n2
    alert(`A soma de ${n1} + ${n2} = ${res}` )
}

function botaoEx2() {
    alert("Vamos fazer a média de dois números:")
let n1 = Number(prompt("Digite o 1º Número:"))
let n2 = Number(prompt("Digite o 2ª Número:"))
let res = (n1 + n2)/2
alert(`A soma de (${n1} + ${n2}) / 2 = ${res}` )
}