
function somar(){
    let n1, n2, result

    n1 = Number (prompt(`1º Número:`))
    n2 = Number (prompt(`2º Número:`))
    result= n1 + n2

    alert(`Resultado:  ${result}`)
}

function subtrair(){
    let n1, n2, result

    n1 = Number (prompt(`1º Número:`))
    n2 = Number (prompt(`2º Número:`))
    result = n1 - n2

    alert(`Resultado:  ${result}`)
}

function multiplicar(){
    let n1, n2, result

    n1 = Number (prompt(`1º Número:`))
    n2 = Number (prompt(`2º Número:`))
    result = n1 * n2

    alert(`Resultado:  ${result}`)
}

function divisao(){
    let n1, n2, result

    n1 = Number (prompt(`1º Número:`))
    n2 = Number (prompt(`2º Número:`))
    result = n1 / n2

    alert(`Resultado:  ${result}`)
}

